try:
    print(1/0)
except:
    print("예외가발생하였습니다")